### ISSUE TITLE
Training should be separate from classifier and persist across processes

### ISSUE THREAD

**Issue by gnidan** [peterldowns/clickbait-classifier#2]
Really neat project! I'm looking into building a browser extension Clickbait "dereferencer", something like the [Stop Clickbait](https://www.facebook.com/StopClickBaitOfficial/) Facebook account, which summarizes baited answers. At this point there seem to be numerous extensions that block Clickbait outright, but I'd rather go on the offensive 😈

**Comment by peterldowns** [comment]
If you send a PR I'd be happy to merge it. You might just want to use this code as a starting point for your own project though. Just added a LICENSE file to make it clear that this is released under the MIT License – do whatever you want with it!
